### ISSUE TITLE
IE Issues

### ISSUE THREAD

**Issue by ugurk** [PredixDev/predix-webapp-starter#1]
It does not work properly on Internet Explorer.
See screenshots:

**Left menu, when screen width is smaller**

![ie11_left_menu_issue](https://cloud.githubusercontent.com/assets/642063/25937768/9ce5e746-3635-11e7-99ab-aa115ce550e5.png)

**Footer is not shown**

![footer-issue](https://cloud.githubusercontent.com/assets/642063/25937693/4e709908-3635-11e7-89b1-a5fb4f2610f7.png)

OS: Windows 7
Browsers: Chrome 58 vs Internet Explorer 11

**Comment by gstroup** [comment]
We've seen the footer issue in IE before.  Haven't seen that left nav issue.  We'll put this on the backlog to fix.  Pull requests welcome too!  :)

**Comment by gstroup** [comment]
fixed with latest release
