### ISSUE TITLE
fontawesome files not found

### ISSUE THREAD

**Issue by Asheq** [PredixDev/predix-webapp-starter#13]
I'm getting some errors in the Chrome dev console. Please see screenshot below:

![image](https://user-images.githubusercontent.com/4657140/29384204-1fb5ec5e-8288-11e7-852a-7ad63ed3a56f.png)

It appears that the icons are appearing in the app itself so this is perhaps a minor issue, but I'm striving to keep the console as clean as possible.

**Comment by turnerth** [comment]
+1

**Comment by gstroup** [comment]
I have a fix for this problem, which we hope to deploy soon.  In public/elements/seed-app/seed-app.scss, around line 27.  Set the font path before importing px-buttons-design.  This is a temporary fix, until we upgrade all the px-components to the latest versions.  Thanks.
```
// Need this font path for some reason, to prevent 404 errors in console.
$fa-font-path: '../../bower_components/font-awesome/fonts';
@import "px-buttons-design/_objects.buttons.scss";
```

**Comment by gstroup** [comment]
fixed with latest release.
