### ISSUE TITLE
predix-webapp-starter v3.1.0 Px-Component Compatibility Issues

### ISSUE THREAD

**Issue by nwchin** [PredixDev/predix-webapp-starter#14]
The following px components have compatibility issues with the most recent release of predix-webapp-starter (v3.1.0):

1) px-spinner
2) px-widget-cards
3) px-tabs
4) px-alert-message
5) px-tooltop
6) px-kpi
7) px-datetime-picker
8) px-file-upload

Performing a bower install for the above components results in dependency issues. Are there any plans update the predix-webapp-starter?

**Comment by gstroup** [comment]
Yes, we are working on a new version of the app now.  It will use all the updated PX components that were just released recently.  Thanks.

**Comment by nwchin** [comment]
Great! Any estimate on when this is expected to be released?

**Comment by gstroup** [comment]
coding is about done.  testing now.  hope to release this week.

**Comment by gstroup** [comment]
New version released today!  using all new versions of px components.
