### ISSUE TITLE
Crashes and Not working in IE (Using IE-11)

### ISSUE THREAD

**Issue by siripuramrj** [PredixDev/predix-webapp-starter#15]
1. Crashes in InternetExplorer-11, very slow, even if i hit on side bar menu it does not respond, responds when I hit enter in the address bar.
2. While logging in with UAA I get a blank white screen with no response. I hit enter again on address bar it responds.
Please Check: 
![whitescreen](https://user-images.githubusercontent.com/31343401/29710293-4d6ee142-89ad-11e7-80ec-004bbafdfae8.PNG)

3. Not getting charts, data, refresh button and lot more on top bar.(https://rmd-ref-app.run.aws-usw02-pr.ice.predix.io/#/rmd)
UserName: app_user_1, Password: app_user_1
Please Check: 
![nodata](https://user-images.githubusercontent.com/31343401/29710254-24222fce-89ad-11e7-93f9-1947d065c679.PNG)

4. Not only in cloud, I tried it in local-host, it still crashes in IE.

**Comment by gstroup** [comment]
Strange. We have automated tests running every day testing Chrome, Firefox, Edge, and IE 11.  We haven't seen failures like this.  We see occasional time outs when the network is slow.  Is this an intermittent problem?  Or is it reproducible?

**Comment by siripuramrj** [comment]
Perfectly reproducible.
These are the steps that I followed to run locally:
1. git clone https://github.com/PredixDev/predix-webapp-starter.git  
2. cd predix-webapp-starter
3. npm install
4. bower install
5. gulp dist
6. gulp (or) gulp --dist //tried both 
In IE, the app hangs and does not work.(Have attached a video)
In Firefox & Chrome it works well.
Note: My laptop config is 8GB, core-i5, 2.2GHZ
         And youtube runs in my IE, why is this APP crashing ? Please help.
Please wait, I will attach the video in a while

**Comment by gstroup** [comment]
we released a new version today, that we've tested in IE 11.  The only known issue is px-breadcrumbs don't work in IE 11.  Let us know if it's still not working for you.
