### ISSUE TITLE
Px worker URLs must be declared before main component is loaded?

### ISSUE THREAD

**Issue by akshayeshenoi** [PredixDev/predix-webapp-starter#18]
The [declaration](https://github.com/PredixDev/predix-webapp-starter/blob/6e27c555b4bb34e637fe0ed674113dc56729af9d/public/_index-inline-loading-script.js#L24
) of global variable Px.vis.workerUrl possibly doesn't take effect since it's done inside the `onMainElementLoaded()` method, which is executed _after_ the main element is loaded. The in-lining of the px-vis element inside the main element causes the `px-vis-worker.js` file to be imported from the wrong location.

**Comment by gstroup** [comment]
Are you seeing errors, like 404 errors loading the px-vis-worker.js file?  I don't see any issues...

**Comment by akshayeshenoi** [comment]
Yes. Happens on my dist version.

**Comment by akshayeshenoi** [comment]
Turns out gulp vulcanizes `px-vis-scheduler.html` for me which puts it in the main element's file. Any clue why that might happen?

**Comment by gstroup** [comment]
Are you importing the `px-vis-scheduler.html` file with an html import, like `<link rel="import ... >`?
If so, then the Polymer CLI will include it in one of the bundled files.

**Comment by akshayeshenoi** [comment]
`px-vis-behavior-d3.html` depends on `px-vis-scheduler.html`, and a lot of other components in turn depend on the former. So that probably causes polymer-build to vulcanize `px-vis-scheduler.html`. 

I tried manually importing `px-vis-scheduler` in `rmd-view.html` (from master) and the dist version throws this error on run-time: 
![image](https://user-images.githubusercontent.com/7693429/30918450-3c5ea094-a3bc-11e7-80ee-8dad3be6bc0c.png)

Moving [these](https://github.com/PredixDev/predix-webapp-starter/blob/6e27c555b4bb34e637fe0ed674113dc56729af9d/public/_index-inline-loading-script.js#L24) lines out of the function fixes the issue, which declares the variable before the vulcanized script is executed.

**Comment by gstroup** [comment]
Interesting.  I have not seen the errors that you show here, using the current webapp-starter.  But what you're saying makes sense.  Moving those global variables outside of the `onMainElementLoaded()` function makes sense.  I'll make that change and do some tests.  Should be included in the next release.  Thanks!

**Comment by gstroup** [comment]
I'm going to keep this open for tracking until the fix is released.  Thanks.

**Comment by gstroup** [comment]
Fixed in v2.0.5.
