### ISSUE TITLE
Block-scoped declarations (let, const, function, class) not yet supported outside strict mode

### ISSUE THREAD

**Issue by Abdelkrim** [PredixDev/predix-webapp-starter#2]
# the issue

1. I have cloned the code on my machine
2. I have installed the required components gulp, node, etc.
3. I have executed `npm install` and `bower install`
4. I have executed `gulp`

# QUESTION

what should I do to run the predix-webapp-starter app?

# logs on the screen after running `gulp`

> predix-webapp-starter@1.0.10 start GE\tuto\predix-webapp-starter
 node server/app.js

> C:\GE\tuto\predix-webapp-starter\server\app.js:188
  let title = "Predix WebApp Starter";
  ^^^

> SyntaxError: **Block-scoped declarations (let, const, function, class) not yet supported outside strict mode**
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:373:25)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Function.Module.runMain (module.js:441:10)
    at startup (node.js:139:18)
    at node.js:968:3

# npm-debug.log

0 info it worked if it ends with ok
1 verbose cli [ 'C:\\app\\nodejs\\node.exe',
1 verbose cli   'C:\\app\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'start' ]
2 info using npm@2.15.0
3 info using node@v4.4.2
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info prestart predix-webapp-starter@1.0.10
6 info start predix-webapp-starter@1.0.10
7 verbose unsafe-perm in lifecycle true
8 info predix-webapp-starter@1.0.10 Failed to exec start script
9 verbose stack Error: predix-webapp-starter@1.0.10 start: `node server/app.js`
9 verbose stack Exit status 1
9 verbose stack     at EventEmitter.<anonymous> (C:\app\nodejs\node_modules\npm\lib\utils\lifecycle.js:217:16)
9 verbose stack     at emitTwo (events.js:87:13)
9 verbose stack     at EventEmitter.emit (events.js:172:7)
9 verbose stack     at ChildProcess.<anonymous> (C:\app\nodejs\node_modules\npm\lib\utils\spawn.js:24:14)
9 verbose stack     at emitTwo (events.js:87:13)
9 verbose stack     at ChildProcess.emit (events.js:172:7)
9 verbose stack     at maybeClose (internal/child_process.js:827:16)
9 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
10 verbose pkgid predix-webapp-starter@1.0.10
11 verbose cwd C:\GE\tuto\predix-webapp-starter
12 error Windows_NT 6.1.7601
13 error argv "C:\\app\\nodejs\\node.exe" "C:\\app\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "start"
14 error node v4.4.2
15 error npm  v2.15.0
16 error code ELIFECYCLE
17 error predix-webapp-starter@1.0.10 start: `node server/app.js`
17 error Exit status 1
18 error Failed at the predix-webapp-starter@1.0.10 start script 'node server/app.js'.
18 error This is most likely a problem with the predix-webapp-starter package,
18 error not with npm itself.
18 error Tell the author that this fails on your system:
18 error     node server/app.js
18 error You can get information on how to open an issue for this project with:
18 error     npm bugs predix-webapp-starter
18 error Or if that isn't available, you can get their info via:
18 error
18 error     npm owner ls predix-webapp-starter
18 error There is likely additional logging output above.
19 verbose exit [ 1, true ]

**Comment by gstroup** [comment]
This is a problem with your version of node.  Looks like the predix-webapp-starter does not work on node 4.x.  Please download the latest LTS version (6.x)  https://nodejs.org/en/ 

You may want to install nvm to allow easy switching between node versions.  https://github.com/creationix/nvm
There's also a windows version called nvm-windows.

**Comment by Abdelkrim** [comment]
Thank you, I have added `"use strict";` on top of each file
