### ISSUE TITLE
Multiple content load on first time run

### ISSUE THREAD

**Issue by Zeuse-Bolt** [PredixDev/predix-webapp-starter#23]
I have been facing this issue for quite a while now in this new seed it still has the same issue as soon I start my way using the web-started kit to make a custom application the multiple content loads on the dashboard on the first run after refreshing it's gone.but for the first user, it's a bad user experience.

**Comment by gstroup** [comment]
Can you give a little more detail on the problem?  What exactly do you see?  Are you seeing the browser make multiple requests for the same content?  Is the page flickering?  Have you modified the app, or are you using it "out of the box"?  Thanks.

**Comment by Zeuse-Bolt** [comment]
well i have use the starter kit as the base for my app and modified it and added some changes this issue only appears as the app is started first time as soon you hit refresh its gone but for the first time it stayes there
![image](https://user-images.githubusercontent.com/19286998/32543608-ed91b6de-c497-11e7-9dc9-557cdde27240.png)

**Comment by gstroup** [comment]
Interesting. I haven't seen that behavior before.  Any errors in the browser console?  You'll probably have to set some breakpoints and debug as the page loads.  Not much else I can think of to solve the problem...
