### ISSUE TITLE
Deprecation of HTML Imports styling the main document

### ISSUE THREAD

**Issue by Zeuse-Bolt** [PredixDev/predix-webapp-starter#26]
im getting this warning message for quite a while now has anyone  given a thought on this
![capture](https://user-images.githubusercontent.com/19286998/37074911-ec2e4c38-21f0-11e8-990a-c806aed6b355.JPG)

**Comment by randyaskin** [comment]
This can be safely ignored. The warning was created by the Chrome team, but the Polymer team already made the necessary changes. More information [here](https://github.com/Polymer/polymer/issues/5008) and [here](https://www.polymer-project.org/blog/2017-10-18-upcoming-changes.html).

**Comment by Zeuse-Bolt** [comment]
thanks for the update @randyaskin .I have sorted this issue out
