### ISSUE TITLE
How to handle with different components having different polymer version

### ISSUE THREAD

**Issue by sravanmca21** [PredixDev/predix-webapp-starter#29]
Hi,

I want to use stacked bar chart in my web-app-starter.
Currently the polymer version is 1.9.0 in web-app-starter, but i am trying to use px-vis-bar-chart
(https://github.com/predixdesignsystem/px-vis-bar-chart/ )which requires  "polymer": "^2.5.0" version.

The app is getting crashed when i installed with latest version of polymer.
How to handle this issue Please help.

**Comment by gstroup** [comment]
Please use components that are compatible with Polymer 1.  You can use this page to find the correct versions:

https://www.predix-ui.com/#/tools/version-finder
