### ISSUE TITLE
Add file upload sample to this

### ISSUE THREAD

**Issue by anilbansal345** [PredixDev/predix-webapp-starter#31]
Dear Team,

I am using this application for one of my predix application. Now we got the request to upload file to a UAA secured service with some request body.

Thanks
Anil Bansal

**Comment by turnerth** [comment]
Thanks for the idea.  The sample app will remain as-is to keep it small.

**Comment by anilbansal345** [comment]
> Thanks for the idea. The sample app will remain as-is to keep it small.

could you please provide me the sample code to upload files. how I can do that.
