### ISSUE TITLE
Issue running starter app

### ISSUE THREAD

**Issue by sansantosh** [PredixDev/predix-webapp-starter#6]
SFO1212394486N:predix-webapp-starter 212394486$ gulp
[03:15:57] Using gulpfile ~/Desktop/EI/predix-webapp-starter/gulpfile.js
[03:15:57] Starting 'default'...
[03:15:57] Starting 'compile:sass'...
Error: Could not import `px-defaults-design/_settings.defaults.scss` from any of the following locations:
  /Users/212394486/Desktop/EI/predix-webapp-starter/public/px-defaults-design/_settings.defaults.scss
  /Users/212394486/Desktop/EI/predix-webapp-starter/public/px-defaults-design/_settings.defaults.scss
  /Users/212394486/Desktop/EI/predix-webapp-starter/public/bower_components/px-defaults-design/_settings.defaults.scss
  /Users/212394486/Desktop/EI/predix-webapp-starter/public/bower_components/px-defaults-design/_settings.defaults.scss
  /Users/212394486/Desktop/EI/predix-webapp-starter/public/bower_components/px-defaults-design/px-defaults-design/_settings.defaults.scss
  /Users/212394486/Desktop/EI/predix-webapp-starter/public/bower_components/px-defaults-design/stylesheets/px-defaults-design/_settings.defaults.scss
  /Users/212394486/Desktop/EI/predix-webapp-starter/public/bower_components/px-defaults-design-sass/stylesheets/px-defaults-design/_settings.defaults.scss
  /Users/212394486/Desktop/EI/predix-webapp-starter/public/bower_components/sass-px-defaults-design/stylesheets/px-defaults-design/_settings.defaults.scss
  /Users/212394486/Desktop/EI/predix-webapp-starter/public/bower_components/px-defaults-design/sass/px-defaults-design/_settings.defaults.scss
  /Users/212394486/Desktop/EI/predix-webapp-starter/public/bower_components/px-defaults-design-sass/sass/px-defaults-design/_settings.defaults.scss
  /Users/212394486/Desktop/EI/predix-webapp-starter/public/bower_components/sass-px-defaults-design/sass/px-defaults-design/_settings.defaults.scss
Error: Could not import `px-colors-design/_settings.colors.scss` from any of the following locations:
  /Users/212394486/Desktop/EI/predix-webapp-starter/public/px-colors-design/_settings.colors.scss
  /Users/212394486/Desktop/EI/predix-webapp-starter/public/px-colors-design/_settings.colors.scss
  /Users/212394486/Desktop/EI/predix-webapp-starter/public/bower_components/px-colors-design/_settings.colors.scss
  /Users/212394486/Desktop/EI/predix-webapp-starter/public/bower_components/px-colors-design/_settings.colors.scss
  /Users/212394486/Desktop/EI/predix-webapp-starter/public/bower_components/px-colors-design/px-colors-design/_settings.colors.scss
  /Users/212394486/Desktop/EI/predix-webapp-starter/public/bower_components/px-colors-design/stylesheets/px-colors-design/_settings.colors.scss
  /Users/212394486/Desktop/EI/predix-webapp-starter/public/bower_components/px-colors-design-sass/stylesheets/px-colors-design/_settings.colors.scss
  /Users/212394486/Desktop/EI/predix-webapp-starter/public/bower_components/sass-px-colors-design/stylesheets/px-colors-design/_settings.colors.scss
  /Users/212394486/Desktop/EI/predix-webapp-starter/public/bower_components/px-colors-design/sass/px-colors-design/_settings.colors.scss
  /Users/212394486/Desktop/EI/predix-webapp-starter/public/bower_components/px-colors-design-sass/sass/px-colors-design/_settings.colors.scss
  /Users/212394486/Desktop/EI/predix-webapp-starter/public/bower_components/sass-px-colors-design/sass/px-colors-design/_settings.colors.scss
Error: Could not import `px-mixins-design/_tools.mixins.scss` from any of the following locations:
  /Users/212394486/Desktop/EI/predix-webapp-starter/public/px-mixins-design/_tools.mixins.scss
  /Users/212394486/Desktop/EI/predix-webapp-starter/public/px-mixins-design/_tools.mixins.scss
  /Users/212394486/Desktop/EI/predix-webapp-starter/public/bower_components/px-mixins-design/_tools.mixins.scss
  /Users/212394486/Desktop/EI/predix-webapp-starter/public/bower_components/px-mixins-design/_tools.mixins.scss
  /Users/212394486/Desktop/EI/predix-webapp-starter/public/bower_components/px-mixins-design/px-mixins-design/_tools.mixins.scss
  /Users/212394486/Desktop/EI/predix-webapp-starter/public/bower_components/px-mixins-design/stylesheets/px-mixins-design/_tools.mixins.scss
  /Users/212394486/Desktop/EI/predix-webapp-starter/public/bower_components/px-mixins-design-sass/stylesheets/px-mixins-design/_tools.mixins.scss
  /Users/212394486/Desktop/EI/predix-webapp-starter/public/bower_components/sass-px-mixins-design/stylesheets/px-mixins-design/_tools.mixins.scss
  /Users/212394486/Desktop/EI/predix-webapp-starter/public/bower_components/px-mixins-design/sass/px-mixins-design/_tools.mixins.scss
  /Users/212394486/Desktop/EI/predix-webapp-starter/public/bower_components/px-mixins-design-sass/sass/px-mixins-design/_tools.mixins.scss
  /Users/212394486/Desktop/EI/predix-webapp-starter/public/bower_components/sass-px-mixins-design/sass/px-mixins-design/_tools.mixins.scss
Error: Could not import `px-normalize-design/_generic.normalize.scss` from any of the following locations:
  /Users/212394486/Desktop/EI/predix-webapp-starter/public/px-normalize-design/_generic.normalize.scss
  /Users/212394486/Desktop/EI/predix-webapp-starter/public/px-normalize-design/_generic.normalize.scss
  /Users/212394486/Desktop/EI/predix-webapp-starter/public/bower_components/px-normalize-design/_generic.normalize.scss
  /Users/212394486/Desktop/EI/predix-webapp-starter/public/bower_components/px-normalize-design/_generic.normalize.scss
  /Users/212394486/Desktop/EI/predix-webapp-starter/public/bower_components/px-normalize-design/px-normalize-design/_generic.normalize.scss
  /Users/212394486/Desktop/EI/predix-webapp-starter/public/bower_components/px-normalize-design/stylesheets/px-normalize-design/_generic.normalize.scss
  /Users/212394486/Desktop/EI/predix-webapp-starter/public/bower_components/px-normalize-design-sass/stylesheets/px-normalize-design/_generic.normalize.scss
  /Users/212394486/Desktop/EI/predix-webapp-starter/public/bower_components/sass-px-normalize-design/stylesheets/px-normalize-design/_generic.normalize.scss
  /Users/212394486/Desktop/EI/predix-webapp-starter/public/bower_components/px-normalize-design/sass/px-normalize-design/_generic.normalize.scss
  /Users/212394486/Desktop/EI/predix-webapp-starter/public/bower_components/px-normalize-design-sass/sass/px-normalize-design/_generic.normalize.scss
  /Users/212394486/Desktop/EI/predix-webapp-starter/public/bower_components/sass-px-normalize-design/sass/px-normalize-design/_generic.normalize.scss
Error: Could not import `px-typography-design/_base.typography.scss` from any of the following locations:
  /Users/212394486/Desktop/EI/predix-webapp-starter/public/px-typography-design/_base.typography.scss
  /Users/212394486/Desktop/EI/predix-webapp-starter/public/px-typography-design/_base.typography.scss
  /Users/212394486/Desktop/EI/predix-webapp-starter/public/bower_components/px-typography-design/_base.typography.scss
  /Users/212394486/Desktop/EI/predix-webapp-starter/public/bower_components/px-typography-design/_base.typography.scss
  /Users/212394486/Desktop/EI/predix-webapp-starter/public/bower_components/px-typography-design/px-typography-design/_base.typography.scss
  /Users/212394486/Desktop/EI/predix-webapp-starter/public/bower_components/px-typography-design/stylesheets/px-typography-design/_base.typography.scss
  /Users/212394486/Desktop/EI/predix-webapp-starter/public/bower_components/px-typography-design-sass/stylesheets/px-typography-design/_base.typography.scss
  /Users/212394486/Desktop/EI/predix-webapp-starter/public/bower_components/sass-px-typography-design/stylesheets/px-typography-design/_base.typography.scss
  /Users/212394486/Desktop/EI/predix-webapp-starter/public/bower_components/px-typography-design/sass/px-typography-design/_base.typography.scss
  /Users/212394486/Desktop/EI/predix-webapp-starter/public/bower_components/px-typography-design-sass/sass/px-typography-design/_base.typography.scss
  /Users/212394486/Desktop/EI/predix-webapp-starter/public/bower_components/sass-px-typography-design/sass/px-typography-design/_base.typography.scss
Error: Could not import `px-headings-design/_base.headings.scss` from any of the following locations:
  /Users/212394486/Desktop/EI/predix-webapp-starter/public/px-headings-design/_base.headings.scss
  /Users/212394486/Desktop/EI/predix-webapp-starter/public/px-headings-design/_base.headings.scss
  /Users/212394486/Desktop/EI/predix-webapp-starter/public/bower_components/px-headings-design/_base.headings.scss
  /Users/212394486/Desktop/EI/predix-webapp-starter/public/bower_components/px-headings-design/_base.headings.scss
  /Users/212394486/Desktop/EI/predix-webapp-starter/public/bower_components/px-headings-design/px-headings-design/_base.headings.scss
  /Users/212394486/Desktop/EI/predix-webapp-starter/public/bower_components/px-headings-design/stylesheets/px-headings-design/_base.headings.scss
  /Users/212394486/Desktop/EI/predix-webapp-starter/public/bower_components/px-headings-design-sass/stylesheets/px-headings-design/_base.headings.scss
  /Users/212394486/Desktop/EI/predix-webapp-starter/public/bower_components/sass-px-headings-design/stylesheets/px-headings-design/_base.headings.scss
  /Users/212394486/Desktop/EI/predix-webapp-starter/public/bower_components/px-headings-design/sass/px-headings-design/_base.headings.scss
  /Users/212394486/Desktop/EI/predix-webapp-starter/public/bower_components/px-headings-design-sass/sass/px-headings-design/_base.headings.scss
  /Users/212394486/Desktop/EI/predix-webapp-starter/public/bower_components/sass-px-headings-design/sass/px-headings-design/_base.headings.scss
Error in plugin 'sass'
Message:
    public/seed-theme.scss
Error: Undefined variable: "$gray9".
        on line 10 of public/seed-theme.scss
>> $px-page-html-background-color: $gray9;
   --------------------------------^

[03:15:57] Finished 'compile:sass' after 62 ms
[03:15:57] Starting 'compile:index'...
[03:15:57] Finished 'compile:index' after 69 ms
[03:15:57] Starting 'serve:dev:start'...
[03:15:57] Finished 'serve:dev:start' after 117 ms
[03:15:57] Starting 'watch:public'...
[03:15:57] Finished 'watch:public' after 21 ms
[03:15:57] Finished 'default' after 273 ms
[03:15:57] [nodemon] 1.11.0
[03:15:57] [nodemon] to restart at any time, enter `rs`
[03:15:57] [nodemon] watching: *.*
[03:15:57] [nodemon] starting `node server/app.js`
/Users/212394486/Desktop/EI/predix-webapp-starter/server/app.js:188
  let title = "Predix WebApp Starter";
  ^^^

SyntaxError: Block-scoped declarations (let, const, function, class) not yet supported outside strict mode
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:387:25)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Function.Module.runMain (module.js:447:10)
    at startup (node.js:146:18)
    at node.js:404:3
[03:15:58] [nodemon] app crashed - waiting for file changes before starting..

**Comment by gstroup** [comment]
I see a few problems here.  First, it looks like you're using an old version of node.  Please use the latest LTS version 6.x.  Second, you appear to be missing a bower component.  After upgrading node, then run `npm install && bower install` again.  Then running `gulp` should work.

**Comment by jeer65** [comment]
Ok After i updated the lated nodejs, running the command
curl -o- https://raw.githubusercontent.com/creationix/nvm/v0.33.2/install.sh | bash
after install NVM then I just updated like
 nvm install node
That it applied to the version v8.4.0

But now that I run the command "gulp"
I got the Sass error see below


[01:33:52] 'compile:sass' errored after 80 ms
[01:33:52] Error: Node Sass does not yet support your current environment: Linux 64-bit with Unsupported runtime (57)
For more information on which environments are supported please see:
https://github.com/sass/node-sass/releases/tag/v3.13.1
    at module.exports (/predix/Documents/Predix Apps/predix-webapp/node_modules/node-sass/lib/binding.js:13:13)
    at Object.<anonymous> (/predix/Documents/Predix Apps/predix-webapp/node_modules/node-sass/lib/index.js:14:35)
    at Module._compile (module.js:573:30)
    at Object.Module._extensions..js (module.js:584:10)
    at Module.load (module.js:507:32)
    at tryModuleLoad (module.js:470:12)
    at Function.Module._load (module.js:462:3)
    at Module.require (module.js:517:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/predix/Documents/Predix Apps/predix-webapp/node_modules/gulp-sass/index.js:187:21)


By the way I'm running using the predix VM from the Predix website

**Comment by jeer65** [comment]
Sorry the reason of my error was because my mistake I edited the package.json and it was locked by the system and that didn't allow to resolve the dependecies "npm install"

**Comment by gstroup** [comment]
Glad you got it working!  Let us know if you see other issues.  Thanks.
